# 5-1. Continuous Random Variables

{% file src="../.gitbook/assets/ch4\_continuous.pdf" caption="Continuous Random Variables" %}

## **1.** The Probability Distribution of a Continuous Random Variable

_The_ **probability distribution of a continuous random variable** _X_ _is an assignment of probabilities to **intervals** of decimal numbers using a function_ $$f(x)$$ , _called a_ density function, _in the following way: the probability that_ _X_ _assumes a value in the interval_ \[a,b\]\[a,b\] _is equal to the area of the region that is bounded above by the graph of the equation_ $$y=f(x)$$ , _bounded below by the_ _x-axis, and bounded on the left and right by the vertical lines through_ _a_ _and_ _b_, _as illustrated in Figure  "Probability Given as Area of a Region under a Curve"_.

![Probability Given as Area of a Region under a Curve](https://saylordotorg.github.io/text_introductory-statistics/section_09/a4a078a33c22b212350844a6cd8789b6.jpg)



> Every density function $$f(x)$$ must satisfy the following two conditions:
>
> 1. For all numbers $$x,$$ $$ f(x)≥0$$ , so that the graph of $$y=f(x)$$ never drops below the _x_-axis.
> 2. The area of the region under the graph of $$y=f(x)$$ and above the _x_-axis is 1.
>
>
>
> For any continuous random variable $$X$$ __: 
>
>       $$P(a≤X≤b)=P(a<X≤b)=P(a≤X<b)=P(a<X<b)$$

## 2. Uniform Distribution



> **균일분포\(Uniform distribution\)**는 유한한 실수 구간 $$[a, b]$$ 에서 동일한 확률로 관측되는 확률변수 $$X$$의 분포이다.
>
>                            $$f(x) = \frac{1}{b-a}, $$   $$a \le X \le b$$ .



> Expected Values and Variance of Uniform Distribution
>
>        $$E(X) = \int_{a}^{b}x\frac{1}{b-a}dx = \frac{b^2-a^2}{2(b-a)}=\frac{a+b}{2}$$ 
>
>        $$E(X^2) = \int_{a}^{b}x^2\frac{1}{b-a}dx = \frac{b^3-a^3}{3(b-a)}=\frac{a^2+ab+b^2}{3}$$ 
>
>        $$Var(X) = E(X^2) - E(X)^2 = \frac{a^2+ab+b^2}{3} - \left ( \frac{a+b}{2} \right )^2 = \frac{(b-a)^2}{12}$$



**EXAMPLE 1.**  A random variable $$X $$ has the **uniform distribution** on the interval $$[0,1]$$ :   
the density function is       
                             $$f(x)=1$$ if _x_ is between 0 and 1   
                      and $$f(x)=0$$ for all other values of $$x$$ ****,   
as shown in Figure  "Uniform Distribution on ".

![Uniform Distribution on \[0, 1\]](../.gitbook/assets/image%20%2880%29.png)

1. Find $$P(X > 0.75)$$ , the probability that $$X $$ assumes a value greater than 0.75.
2. Find $$P(X ≤ 0.2)$$ , the probability that $$X $$ assumes a value less than or equal to 0.2.
3. Find $$P(0.4 < X < 0.7)$$ , the probability that $$X $$ assumes a value between 0.4 and 0.7.

**\[ Solution \]**

![](../.gitbook/assets/image%20%28167%29.png)

1. $$P(X > 0.75)$$ is the area of the rectangle of height 1 and base length $$1−0.75=0.25$$ ****, hence is $$base×height=(0.25)⋅(1)=0.25$$ . See Figure 5.3 "Probabilities from the Uniform Distribution on "\(a\).
2. $$P(X ≤ 0.2)$$ is the area of the rectangle of height 1 and base length $$0.2−0=0.2$$ , hence is $$base×height=(0.2)⋅(1)=0.2$$ . See Figure 5.3 "Probabilities from the Uniform Distribution on "\(b\).
3. $$P(0.4 < X < 0.7)$$ is the area of the rectangle of height 1 and length $$0.7−0.4=0.3$$ , hence is $$base×height=(0.3)⋅(1)=0.3$$ . See Figure 5.3 "Probabilities from the Uniform Distribution on "\(c\).

{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

# 0. Probability Distribution Function
fx <- function(x) dunif(x, 0, 1)

win.graph(7, 6); par(mfrow=c(1,1));

# E(X), Var(X) and Plot
cont.exp(fx, -0.2, 1.2, prt=TRUE, plot=TRUE)

# 1. P(X>0.75)
punif(0.75, min=0, max=1, lower.tail=FALSE)

# 2. P(X<0.2)
punif(0.2, min=0, max=1, lower.tail=TRUE)

# 3. P(0.4<X<0.7) = P(X<0.7) - P(X<0.4)
punif(0.7, min=0, max=1, lower.tail=TRUE) - punif(0.4, min=0, max=1, lower.tail=TRUE) 
```
{% endtab %}

{% tab title="Prob. Distribution Plot" %}
![](../.gitbook/assets/image%20%2876%29.png)
{% endtab %}

{% tab title="1. P\(X>0.75\)" %}
```text
> # 1. P(X>0.75)
> punif(0.75, min=0, max=1, lower.tail=FALSE)
## [1] 0.25
```
{% endtab %}

{% tab title="2. P\(X<0.2\)" %}
```text
> # 2. P(X<0.2)
> punif(0.2, min=0, max=1, lower.tail=TRUE)
## [1] 0.2
```
{% endtab %}

{% tab title="3. P\(0.4<X<0.7\)" %}
```text
> # 3. P(0.4<X<0.7) = P(X<0.7) - P(X<0.4)
> punif(0.7, min=0, max=1, lower.tail=TRUE) - punif(0.4, min=0, max=1, lower.tail=TRUE) 
## [1] 0.3
```
{% endtab %}
{% endtabs %}

\*\*\*\*

**EXAMPLE 2**. A man arrives at a bus stop at a random time \(that is, with no regard for the scheduled service\) to catch the next bus. Buses run every 30 minutes without fail, hence the next bus will come any time during the next 30 minutes with evenly distributed probability \(a uniform distribution\). Find the probability that a bus will come within the next 10 minutes.

**\[ Solution \]**

The graph of the density function is a horizontal line above the interval from 0 to 30 and is the _x_-axis everywhere else. Since the total area under the curve must be 1, the height of the horizontal line is 1/30. See Figure 5.4 "Probability of Waiting At Most 10 Minutes for a Bus". The probability sought is $$P(0≤X≤10)$$ . 

By definition, this probability is the area of the rectangular region bounded above by the horizontal line $$f(x)=1∕30,$$ bounded below by the _x_-axis, bounded on the left by the vertical line at 0 \(the _y_-axis\), and bounded on the right by the vertical line at 10. This is the shaded region in Figure 5.4 "Probability of Waiting At Most 10 Minutes for a Bus". Its area is the base of the rectangle times its height, $$10⋅(1∕30)=1∕3$$ . 

Thus $$P(0≤X≤10)=1∕3$$ .  


![Probability of Waiting At Most 10 Minutes for a Bus](../.gitbook/assets/image%20%28212%29.png)

{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

min <- 0
max <- 30

# 0. Probability Distribution Function
fx <- function(x) dunif(x, min, max)

# E(X), Var(X) and Plot
t <- (max-min) * 0.2 
cont.exp(fx, min-t, max+t, prt=TRUE, plot=TRUE)

# 1. P(X<10)
punif(10, min=min, max=max, lower.tail=TRUE)

```
{% endtab %}

{% tab title="Prob. Distribution Plot" %}
![](../.gitbook/assets/image%20%28231%29.png)
{% endtab %}

{% tab title="P\(0≤X≤10\)" %}
```text
> punif(10, min=min, max=max, lower.tail=TRUE)
## [1] 0.3333333
```
{% endtab %}
{% endtabs %}

## 3. Uniform Distribution in R

| Function |  | parameters |
| :--- | :--- | :--- |
| density function | d | `dunif(x, min, max)` |
| cumulative distribution function | p | `punif(q, min, max, lower.tail =TRUE/FALSE` |
| quantile function | q | `qunif(p, min, max, lower.tail = TRUE/FALSE` |
| random nunber generation | r | `runif(n, min, max)` |



### 3-1. Uniform Distribution Plot

`dunif()`

* Uniform Distribution of $$0 \le X \le 10$$

{% tabs %}
{% tab title="R Source" %}
```
library(ggplot2)

# uniform distribution plot (min=0, max=10)
# fun = dunif
ggplot(data.frame(x=c(-2,20)), aes(x=x)) +
stat_function(fun=dunif, args=list(min = 0, max = 10), 
        colour="black", size=1) +
ggtitle("Uniform Distribution of (min=1, max=10)")

```
{% endtab %}

{% tab title="Plot" %}
![](../.gitbook/assets/image%20%2872%29.png)
{% endtab %}
{% endtabs %}

 

### 3-2. Cumulative Uniform Distribution Plot

`punif()`

* Uniform Distribution of $$0 \le X \le 10$$

{% tabs %}
{% tab title="R Source" %}
```
# Cumulative Uniform distribution plot) : fun = punif 

ggplot(data.frame(x=c(-2,20)), aes(x=x)) + 
stat_function(fun=punif, args=list(min = 0, max = 10), 
               colour="black", size=1) + 
ggtitle("Cumulative Uniform Distribution of (min=0, max=10)")
```
{% endtab %}

{% tab title="Plot" %}
![](../.gitbook/assets/image%20%2811%29.png)
{% endtab %}
{% endtabs %}



### 3-3. Probability Calculation

* Uniform Distribution of $$0 \le X \le 10$$, $$X$$ from 0 to 3"

                             min = 0, max = 10 =&gt; $$P(0 <X<3) = ?$$ 

{% tabs %}
{% tab title="R Source" %}
```
# 확률 값 계산 : punif()
# punif(q, min, max, lower.tail = TRUE/FALSE)
punif(3, min=0, max=10, lower.tail=TRUE)

# Uniform Distribution of (min=1, max=10), x from 0 to 3"
ggplot(data.frame(x=c(-2,20)), aes(x=x)) +
stat_function(fun=dunif, args=list(min = 0, max = 10), colour="black", size=1) +
annotate("rect", xmin=0, xmax=3, ymin=0, ymax=0.1, alpha=0.2, fill="yellow") +
ggtitle("Uniform Distribution of (min=1, max=10), x from 0 to 3")
```
{% endtab %}

{% tab title="Probability" %}
```
> punif(3, min=0, max=10, lower.tail=TRUE)
## [1] 0.3
```
{% endtab %}

{% tab title="P\(0<X<3\) : Plot" %}
![](../.gitbook/assets/image%20%28149%29.png)
{% endtab %}
{% endtabs %}



### 3-4. Quartiles

`qunif(p, min, max, lower.tail=TRUE/FALSE)`

* Uniform Distribution of $$0 \le X \le 10$$

{% tabs %}
{% tab title="R Source" %}
```
qunif(0.3, min=0, max=10, lower.tail = TRUE)
```
{% endtab %}

{% tab title="quartile" %}
```
> qunif(0.3, min=0, max=10, lower.tail = TRUE)
## [1] 3
```
{% endtab %}
{% endtabs %}



### 3-5. Random Number Generation

`runif(n=100, min=0, max = 10)`

{% tabs %}
{% tab title="R Source" %}
```
# Random Number Generation
ru_100 <- runif(n=100, min=0, max = 10) ; ru_100

# density plot of runif(n=100, min=0, max = 10) & adding line of 0.1 uniform probability
hist(ru_100, freq=FALSE, breaks=10, col="yellow", ylim=c(0, 0.15))
abline(h=0.1, lty=3, lwd=3, col="red")
 
```
{% endtab %}

{% tab title="Random Number" %}
```
> ru_100 <- runif(n=100, min=0, max = 10); ru_100
##   [1] 1.97018452 3.71806505 7.41606720 8.48671408 0.47856458 3.60782547 5.10053850 6.42437469 4.00373441 4.03389579 1.77176371 5.67226059 9.03927102 9.39120243 0.94763774 8.59339938 1.86347542 9.00808273 7.53425727 0.18291435
##  [21] 1.10629222 2.14713704 3.61159600 9.91049072 3.97496036 1.21901205 1.99912945 2.29975202 7.91296603 4.59785103 7.19803239 0.69360516 9.75771851 6.12264345 4.95634087 6.48131121 2.58554254 2.17646432 1.46618064 6.81097950
##  [41] 2.21970354 0.97172896 9.06870417 0.45217870 0.67816859 3.33815603 2.48469822 0.43481027 4.69975307 6.09926291 3.16123004 2.60607698 9.47217206 1.41006090 8.04198232 3.13095264 0.24097621 8.39983448 7.62463219 4.76048162
##  [61] 3.04053000 7.10983243 8.16657863 5.57156257 0.10561342 5.79480714 4.82581432 8.82737239 3.05016402 0.90337332 9.90451497 4.08636837 5.81762119 7.91393302 2.50766472 9.94363813 0.07042486 5.73481684 6.59473334 7.20472657
##  [81] 4.69420254 1.31388268 4.45257513 4.29468046 6.15421702 1.19002639 7.00127259 3.90113476 8.53588901 9.12484395 8.33627391 8.85767937 4.97731321 3.21789454 2.33261707 3.71808882 1.03884319 0.84080657 3.43642535 3.42259390
```
{% endtab %}

{% tab title="Plot" %}
![](../.gitbook/assets/image%20%28136%29.png)
{% endtab %}
{% endtabs %}



## 4. Normal Distributions

The formula for $$f(x) $$ contains two parameters $$μ$$ and $$σ$$ that can be assigned any specific numerical values, so long as $$σ$$ is positive. We will not need to know the formula for $$f(x)$$ , but for those who are interested it is

                                                               $$f(x)= \frac {1}{\sqrt{ 2 \pi} \sigma } e^ {-\frac{1}{2} \left ( \frac{x-\mu}{\sigma }  \right ) ^2 } $$ 

where $$π≈3.14159$$ and $$e ≈ 2.71828$$ is the base of the natural logarithms.

![Bell Curves with &#x3C3; = 0.25 and Different Values of &#x3BC;](../.gitbook/assets/image%20%28159%29.png)

{% tabs %}
{% tab title="R Source" %}
```text
library(ggplot2)

# uniform distribution plot (min=0, max=10)
# fun = dnorm
mu <- c(-2, -1, 1)

ggplot(data.frame(x=c(-4,4)), aes(x=x)) +
stat_function(fun=dnorm, args=list(mean = mu[1], sd = 0.25), 
        colour="black", size=1) +
stat_function(fun=dnorm, args=list(mean = mu[2], sd = 0.25), 
        colour="blue", size=1) +
stat_function(fun=dnorm, args=list(mean = mu[3], sd = 0.25), 
        colour="red", size=1) +
ggtitle("Normal Distribution of (mu=c(-2, -1, 1), sigma=0.25)")
```
{% endtab %}

{% tab title="Plot" %}
![](../.gitbook/assets/image%20%28108%29.png)
{% endtab %}
{% endtabs %}



The value of $$σ$$ determines whether the bell curve is tall and thin or short and squat, subject always to the condition that the total area under the curve be equal to 1. 



![Bell Curves with &#x3BC; = 6 and Different Values of &#x3C3;](../.gitbook/assets/image%20%28229%29.png)

{% tabs %}
{% tab title="R Source" %}
```text
library(ggplot2)

# uniform distribution plot (min=0, max=10)
# fun = dnorm
mu <- 6
sd <- c(0.5, 1, 2)

ggplot(data.frame(x=c(-2,14)), aes(x=x)) +
stat_function(fun=dnorm, args=list(mean = mu, sd = sd[1]), 
        colour="black", size=1) +
stat_function(fun=dnorm, args=list(mean = mu, sd = sd[2]), 
        colour="blue", size=1) +
stat_function(fun=dnorm, args=list(mean = mu, sd = sd[3]), 
        colour="red", size=1) +
ggtitle("Normal Distribution of (mean=6, sigma=c(0.5, 1, 2))")
```
{% endtab %}

{% tab title="Plot" %}
![](../.gitbook/assets/image%20%28123%29.png)
{% endtab %}
{% endtabs %}



> _The probability distribution corresponding to the density function for the bell curve with parameters_ $$μ$$ _and_ $$σ$$ _is called the_ **normal distribution** _with mean_ $$μ$$ _and standard deviation_ $$σ$$ .



> _A continuous random variable whose probabilities are described by the normal distribution with mean_ $$μ$$ _and standard deviation_ $$σ $$ _is called a_ **normally distributed random variable, or a normal random variable** _for short, with mean_ $$μ$$ _and standard deviation_ $$σ$$  : $$X \sim N(\mu , \sigma )$$ .



> The density curve for the normal distribution is **symmetric about the mean**.



![Density Function for a Normally Distributed Random Variable with Mean &#x3BC; and Standard Deviation &#x3C3;](../.gitbook/assets/image%20%2874%29.png)



**EXAMPLE 3.** Heights of 25-year-old men in a certain region have mean 69.75 inches and standard deviation 2.59 inches. These heights are approximately normally distributed. Thus the height _X_ of a randomly selected 25-year-old man is a normal random variable with mean _μ_ = 69.75 and standard deviation _σ_ = 2.59. Sketch a qualitatively accurate graph of the density function for _X_. Find the probability that a randomly selected 25-year-old man is more than 69.75 inches tall.

**\[ Solution \]**

Since the total area under the curve is 1, by symmetry the area to the right of 69.75 is half the total, or 0.5. But this area is precisely the probability $$P(X > 69.75)$$, the probability that a randomly selected 25-year-old man is more than 69.75 inches tall.

![Density Function for Heights of 25-Year-Old Men](../.gitbook/assets/image%20%28225%29.png)

{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

# 1. Compute P(X<=69.75
pnorm(69.75, mean=69.75, sd=2.59)

# 2. Plot
norm.trans(69.75, 2.59, a=0, b=69.75)

```
{% endtab %}

{% tab title="P\(X < 69.75\)" %}
```text
> pnorm(69.75, mean=69.75, sd=2.59)
## [1] 0.5
```
{% endtab %}

{% tab title="Plot" %}
![](../.gitbook/assets/image%20%28157%29.png)
{% endtab %}
{% endtabs %}



We will learn how to compute other probabilities in the next two sections.



### 4-1. Random Number Generation & Plotting using R

* Random Number Generation : `dnorm(x, mena = , sd = )`
* Plotting : `plot(x, dnorm())`

mean $$μ $$ = 69.75 , standard deviation $$σ $$ = 2.59. 

{% tabs %}
{% tab title="R Source" %}
```
# Normal distribution plot, X~N(69.76, 2.59)
mu <- 69.75
sigma <- 2.59
x <- seq((mu - 6 * sigma), (mu + 6 * sigma), length=200) # x-axis values
dnorm(x, mean=mu, sd=sigma)   # random number

main_title <- paste("Normal Distribution, X ~ N(", mu,",",sigma,")", sep="")
ylab_title <- paste("dnorm(x, mean = ", mu, ", sd = ", sigma,")", sep="")

plot(x, dnorm(x, mean=mu, sd=sigma), 
        type='l', 
        main=main_title,
        ylab=ylab_title)
abline(v=mu, col="yellow")
abline(h=0, col="gray")
```
{% endtab %}

{% tab title="Random Number" %}
```
> dnorm(x, mean=mu, sd=sigma)   # random number
  [1] 2.345901e-09 3.362418e-09 4.801916e-09 6.832792e-09 9.687297e-09 1.368447e-08 1.926078e-08 2.701100e-08 3.774229e-08 5.254562e-08 7.288962e-08 1.007432e-07 1.387351e-07 1.903610e-07 2.602497e-07 3.545057e-07 4.811463e-07
 [18] 6.506565e-07 8.766924e-07 1.176965e-06 1.574347e-06 2.098255e-06 2.786358e-06 3.686687e-06 4.860226e-06 6.384067e-06 8.355245e-06 1.089536e-05 1.415615e-05 1.832606e-05 2.363818e-05 3.037944e-05 3.890149e-05 4.963333e-05
 [35] 6.309595e-05 7.991905e-05 1.008602e-04 1.268266e-04 1.588991e-04 1.983597e-04 2.467211e-04 3.057594e-04 3.775497e-04 4.645038e-04 5.694102e-04 6.954756e-04 8.463683e-04 1.026261e-03 1.239872e-03 1.492508e-03 1.790100e-03
 [52] 2.139236e-03 2.547187e-03 3.021926e-03 3.572133e-03 4.207191e-03 4.937165e-03 5.772763e-03 6.725285e-03 7.806537e-03 9.028735e-03 1.040438e-02 1.194610e-02 1.366650e-02 1.557790e-02 1.769218e-02 2.002048e-02 2.257296e-02
 [69] 2.535849e-02 2.838435e-02 3.165595e-02 3.517649e-02 3.894668e-02 4.296445e-02 4.722465e-02 5.171887e-02 5.643521e-02 6.135812e-02 6.646833e-02 7.174278e-02 7.715472e-02 8.267373e-02 8.826598e-02 9.389446e-02 9.951931e-02
 [86] 1.050983e-01 1.105871e-01 1.159403e-01 1.211114e-01 1.260539e-01 1.307219e-01 1.350707e-01 1.390577e-01 1.426427e-01 1.457890e-01 1.484639e-01 1.506391e-01 1.522914e-01 1.534029e-01 1.539618e-01 1.539618e-01 1.534029e-01
[103] 1.522914e-01 1.506391e-01 1.484639e-01 1.457890e-01 1.426427e-01 1.390577e-01 1.350707e-01 1.307219e-01 1.260539e-01 1.211114e-01 1.159403e-01 1.105871e-01 1.050983e-01 9.951931e-02 9.389446e-02 8.826598e-02 8.267373e-02
[120] 7.715472e-02 7.174278e-02 6.646833e-02 6.135812e-02 5.643521e-02 5.171887e-02 4.722465e-02 4.296445e-02 3.894668e-02 3.517649e-02 3.165595e-02 2.838435e-02 2.535849e-02 2.257296e-02 2.002048e-02 1.769218e-02 1.557790e-02
[137] 1.366650e-02 1.194610e-02 1.040438e-02 9.028735e-03 7.806537e-03 6.725285e-03 5.772763e-03 4.937165e-03 4.207191e-03 3.572133e-03 3.021926e-03 2.547187e-03 2.139236e-03 1.790100e-03 1.492508e-03 1.239872e-03 1.026261e-03
[154] 8.463683e-04 6.954756e-04 5.694102e-04 4.645038e-04 3.775497e-04 3.057594e-04 2.467211e-04 1.983597e-04 1.588991e-04 1.268266e-04 1.008602e-04 7.991905e-05 6.309595e-05 4.963333e-05 3.890149e-05 3.037944e-05 2.363818e-05
[171] 1.832606e-05 1.415615e-05 1.089536e-05 8.355245e-06 6.384067e-06 4.860226e-06 3.686687e-06 2.786358e-06 2.098255e-06 1.574347e-06 1.176965e-06 8.766924e-07 6.506565e-07 4.811463e-07 3.545057e-07 2.602497e-07 1.903610e-07
[188] 1.387351e-07 1.007432e-07 7.288962e-08 5.254562e-08 3.774229e-08 2.701100e-08 1.926078e-08 1.368447e-08 9.687297e-09 6.832792e-09 4.801916e-09 3.362418e-09 2.345901e-09
>
```
{% endtab %}

{% tab title="Plot" %}
![](../.gitbook/assets/image%20%28164%29.png)
{% endtab %}
{% endtabs %}

