# 5-2. The Standard Normal Distribution

## 1. A Standard Normal Random Variable 

> _**A**_ **standard Normal Random Variable** _is a normally distributed random variable with mean_ $$μ = 0$$ _and standard deviation_ $$σ = 1$$ . _It will always be denoted by the letter_ $$Z$$  : $$Z \sim N(0, 1)$$ .

> $$X \sim N(\mu, \sigma^2 )$$일 때, $$Z = \frac {(X-\mu )}{\sigma }$$ 라 하면,  $$Z \sim N(0, 1)$$이다. 즉, 정규분포를 따르는 확률변수를 표준화하면, 그 확률변수는 표준정규분포를 따른다.



![Density Curve for a Standard Normal Random Variable](../.gitbook/assets/image%20%28145%29.png)



**EXAMPLE 4.** 확률변수 $$X$$가 $$N(2, 2^2)$$ 을 따를 때, $$P(-1<X<4)$$ 를 구하시오.

**\[ Solution \]**

$$P(-1<X<4) = P( \frac {-1-2}{2} < \frac{X-2}{2} <\frac {4-2}{2} $$

                                   $$= P(-1.5 <Z<1) = 0.8413 - 0.0668=0.7745$$ ****

{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

# 1-1. Compute P(-1<X<4)
a <- -1; b <- 4
pnorm(b) - pnorm(a)

# 1-2. Plot
norm.trans(0, 1, a=a, b=b)
```
{% endtab %}

{% tab title="P\(-1<X<4\)" %}
```text
> # 1-1. Compute P(-1<X<4)
> mu <- 2; sd <- 2
> a <- -1; b <- 4
> pnorm(b, mean=mu, sd=sd) - pnorm(a, mean=mu, sd=sd)
## [1] 0.7745375
```
{% endtab %}

{% tab title="Plot" %}
```text
> # 1-2. Plot
> norm.trans(mu, sd, a=a, b=b)
## Pr(-1 < X < 4) =  0.7745375 
## Pr(-1.5 < Z < 1) =  0.7745375 
```

![](../.gitbook/assets/image%20%2819%29.png)
{% endtab %}
{% endtabs %}



**EXAMPLE 5.** 표준정규분포의 누적확률 표와 그래프를 작성하시오.

**\[ Solution \]**

{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

# 1. Table
# 표준정규 누적확률 ( 0 ~ 2.49 ), 0.01 단위, 10개 열
pv <- matrix(pnorm(0:299/100), ncol=10, byrow=TRUE)
colnames(pv) <- 0:9/100; rownames(pv) <- 0:29/10
(round(pv, 4))

# 2. Plot cdf
# 누적확률 그래프에 표시할 점 지정
zp <- seq(-2, 2, by=0.5)

# 누적확률 그래프 작성 : snorm.cdf()
snorm.cdf(zp)
```
{% endtab %}

{% tab title="Table" %}
```text
> # 1. Table
> # 표준정규 누적확률 ( 0 ~ 2.49 ), 0.01 단위, 10개 열
> pv <- matrix(pnorm(0:299/100), ncol=10, byrow=TRUE)
> colnames(pv) <- 0:9/100; rownames(pv) <- 0:29/10
> (round(pv, 4))
##          0   0.01   0.02   0.03   0.04   0.05   0.06   0.07   0.08   0.09
## 0   0.5000 0.5040 0.5080 0.5120 0.5160 0.5199 0.5239 0.5279 0.5319 0.5359
## 0.1 0.5398 0.5438 0.5478 0.5517 0.5557 0.5596 0.5636 0.5675 0.5714 0.5753
## 0.2 0.5793 0.5832 0.5871 0.5910 0.5948 0.5987 0.6026 0.6064 0.6103 0.6141
## 0.3 0.6179 0.6217 0.6255 0.6293 0.6331 0.6368 0.6406 0.6443 0.6480 0.6517
## 0.4 0.6554 0.6591 0.6628 0.6664 0.6700 0.6736 0.6772 0.6808 0.6844 0.6879
## 0.5 0.6915 0.6950 0.6985 0.7019 0.7054 0.7088 0.7123 0.7157 0.7190 0.7224
## 0.6 0.7257 0.7291 0.7324 0.7357 0.7389 0.7422 0.7454 0.7486 0.7517 0.7549
## 0.7 0.7580 0.7611 0.7642 0.7673 0.7704 0.7734 0.7764 0.7794 0.7823 0.7852
## 0.8 0.7881 0.7910 0.7939 0.7967 0.7995 0.8023 0.8051 0.8078 0.8106 0.8133
## 0.9 0.8159 0.8186 0.8212 0.8238 0.8264 0.8289 0.8315 0.8340 0.8365 0.8389
## 1   0.8413 0.8438 0.8461 0.8485 0.8508 0.8531 0.8554 0.8577 0.8599 0.8621
## 1.1 0.8643 0.8665 0.8686 0.8708 0.8729 0.8749 0.8770 0.8790 0.8810 0.8830
## 1.2 0.8849 0.8869 0.8888 0.8907 0.8925 0.8944 0.8962 0.8980 0.8997 0.9015
## 1.3 0.9032 0.9049 0.9066 0.9082 0.9099 0.9115 0.9131 0.9147 0.9162 0.9177
## 1.4 0.9192 0.9207 0.9222 0.9236 0.9251 0.9265 0.9279 0.9292 0.9306 0.9319
## 1.5 0.9332 0.9345 0.9357 0.9370 0.9382 0.9394 0.9406 0.9418 0.9429 0.9441
## 1.6 0.9452 0.9463 0.9474 0.9484 0.9495 0.9505 0.9515 0.9525 0.9535 0.9545
## 1.7 0.9554 0.9564 0.9573 0.9582 0.9591 0.9599 0.9608 0.9616 0.9625 0.9633
## 1.8 0.9641 0.9649 0.9656 0.9664 0.9671 0.9678 0.9686 0.9693 0.9699 0.9706
## 1.9 0.9713 0.9719 0.9726 0.9732 0.9738 0.9744 0.9750 0.9756 0.9761 0.9767
## 2   0.9772 0.9778 0.9783 0.9788 0.9793 0.9798 0.9803 0.9808 0.9812 0.9817
## 2.1 0.9821 0.9826 0.9830 0.9834 0.9838 0.9842 0.9846 0.9850 0.9854 0.9857
## 2.2 0.9861 0.9864 0.9868 0.9871 0.9875 0.9878 0.9881 0.9884 0.9887 0.9890
## 2.3 0.9893 0.9896 0.9898 0.9901 0.9904 0.9906 0.9909 0.9911 0.9913 0.9916
## 2.4 0.9918 0.9920 0.9922 0.9925 0.9927 0.9929 0.9931 0.9932 0.9934 0.9936
## 2.5 0.9938 0.9940 0.9941 0.9943 0.9945 0.9946 0.9948 0.9949 0.9951 0.9952
## 2.6 0.9953 0.9955 0.9956 0.9957 0.9959 0.9960 0.9961 0.9962 0.9963 0.9964
## 2.7 0.9965 0.9966 0.9967 0.9968 0.9969 0.9970 0.9971 0.9972 0.9973 0.9974
## 2.8 0.9974 0.9975 0.9976 0.9977 0.9977 0.9978 0.9979 0.9979 0.9980 0.9981
## 2.9 0.9981 0.9982 0.9982 0.9983 0.9984 0.9984 0.9985 0.9985 0.9986 0.9986

```
{% endtab %}

{% tab title="Plot" %}
```text
> # 2. Plot cdf
> # 누적확률 그래프에 표시할 점 지정
> zp <- seq(-2, 2, by=0.5)
> 
> # 누적확률 그래프 작성 : snorm.cdf()
> snorm.cdf(zp)
```

![](../.gitbook/assets/image%20%28107%29.png)
{% endtab %}
{% endtabs %}



**EXAMPLE 5.** 표준정규분포에서 0 을 중심으로 $$\pm k$$  사이에 들어갈 확률을 나타내는 그래프를 작성하시오.

**\[ Solution \]**

{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

# 1. Plot cdf
# 누적확률 그래프에 표시할 점 지정
zp <- 1:4
snorm.cdf(zp)
```
{% endtab %}

{% tab title="Plot" %}
```text
> # 누적확률 그래프 작성 : snorm.cdf()
> snorm.cdf(zp)
> zp <- 1:4
> snorm.cdf(zp)
```

![](../.gitbook/assets/image%20%2898%29.png)
{% endtab %}
{% endtabs %}



**EXAMPLE 6.** 누적확률 0.5%, 1.0%, 2.5%, 5.0%, 10% ~ 90%, 95%, 97.5%, 99%, 99.5%에 대한 표준정규분포의 분위수 표를 작성하시오.

**\[ Solution \]**

{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

# 분위수 계산/표시 누적확률
pv <- c(0.005, 0.01, 0.025, 0.05, 1:9/10, 0.95, 0.975, 0.99, 0.995)

# 표준정규 분위수 작성 : snorm.quant()
snorm.quant(pv, pv)
```
{% endtab %}

{% tab title="Table & Plot" %}
```text
> # 분위수 계산/표시 누적확률
> pv <- c(0.005, 0.01, 0.025, 0.05, 1:9/10, 0.95, 0.975, 0.99, 0.995)
> 
> # 표준정규 분위수 작성 : snorm.quant()
> snorm.quant(pv, pv)
##   0.005    0.01   0.025    0.05     0.1     0.2     0.3     0.4     0.5 
## -2.5758 -2.3263 -1.9600 -1.6449 -1.2816 -0.8416 -0.5244 -0.2533  0.0000 
##     0.6     0.7     0.8     0.9    0.95   0.975    0.99   0.995 
##  0.2533  0.5244  0.8416  1.2816  1.6449  1.9600  2.3263  2.5758 
```

![](../.gitbook/assets/image%20%28175%29.png)
{% endtab %}
{% endtabs %}



**EXAMPLE 7.** 20대 남성의 신장이 평균 175, 분산 64인 정규분포를 따른다고 할 때, 20대 남성 중 180과 185 사이의 신장을 갖는 비율을 구하시오.

**\[ Solution \]**

$$X \sim N(175, 8^2 )$$**,**

$$P(180<X<185) =  p( \frac{180-175}{8} < \frac{X-175}{8} < \frac{185-175}{8} )$$                                          ****$$= P(0.625 < Z < 1.25) = P(Z<1.25) - P(Z<0.625) = 0.8944-0.7340 = 0.1604$$ 

{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

# 1-1. Compute P(180<X<185)
mu <- 175; sd <- 8
a <- 180; b <- 185
pnorm(b, mean=mu, sd=sd) - pnorm(a, mean=mu, sd=sd)

# 1-2. Plot
norm.trans(mu, sd, a=a, b=b)
```
{% endtab %}

{% tab title="P\(180<X<185\)" %}
```text
> # 1-1. Compute P(180<X<185)
> mu <- 175; sd <- 8
> a <- 180; b <- 185
> pnorm(b, mean=mu, sd=sd) - pnorm(a, mean=mu, sd=sd)
## [1] 0.1603358
```
{% endtab %}

{% tab title="Plot" %}
```text
> # 1-2. Plot
> norm.trans(mu, sd, a=a, b=b)
## Pr(180 < X < 185) =  0.1603358 
## Pr(0.625 < Z < 1.25) =  0.1603358 
```

![](../.gitbook/assets/image%20%28155%29.png)
{% endtab %}
{% endtabs %}



**EXAMPLE 8.** A사 Q모델의 엔진 수명은 평균 10년, 표준편차가 1.5년인 정규분포를 따른다고 알려져 있다. Q 모델 엔진의 무상보증비율을 5% 이내로 유지해야 한다면, 무상보증기간은 최대 몇 년까지 가능하겠는가?

**\[ Solution \]**

$$X \sim N(10, 1.5^2 )$$**,** 무상보증기간을 $$m$$이라 하면, $$P(X<m) \le 0.05)$$ 를 만족해야 하므로,  

$$P(X<m) = P( Z < \frac{m-10}{1.5}) =0.05$$ ==&gt; $$\frac{m-10}{1.5} \le -1.645, \therefore m \le 7.5325$$ 

따라서 무상보증기간은 최대 약 7.53년이 된다.

{% tabs %}
{% tab title="R Source" %}
```text
qnorm(0.05, mean=10, sd=1.5)
```
{% endtab %}

{% tab title="m" %}
```text
> qnorm(0.05, mean=10, sd=1.5)
## [1] 7.53272
```
{% endtab %}
{% endtabs %}



## 2. Cumulative Probability

 To compute probabilities for $$Z$$ we will not work with its density function directly but instead read probabilities out of Figure  "Cumulative Normal Probability" in [Chapter 12 "Appendix"](https://saylordotorg.github.io/text_introductory-statistics/s16-appendix.html). The tables are tables of _**cumulative**_ **probabilities**; their entries are probabilities of the form $$P(Z<z)$$ . The use of the tables will be explained by the following series of examples.



**EXAMPLE 4.** Find the probabilities indicated, where as always $$Z$$ denotes a standard normal random variable.

1. $$P(Z < 1.48)$$ .
2. $$P(Z< −0.25)$$ .

**\[ Solution \]**

1. Figure 5.10 "Computing Probabilities Using the Cumulative Table" shows how this probability is read directly from the table without any computation required. The digits in the ones and tenths places of 1.48, namely 1.4, are used to select the appropriate row of the table; the hundredths part of 1.48, namely 0.08, is used to select the appropriate column of the table. The four decimal place number in the interior of the table that lies in the intersection of the row and column selected, 0.9306, is the probability sought: $$P(Z<1.48)=0.9306.$$  
2. The minus sign in −0.25 makes no difference in the procedure; the table is used in exactly the same way as in part \(a\): the probability sought is the number that is in the intersection of the row with heading −0.2 and the column with heading 0.05, the number 0.4013. Thus $$P(Z < −0.25) = 0.4013$$ .

Figure 5.10 ****Computing Probabilities Using the Cumulative Table

![](https://saylordotorg.github.io/text_introductory-statistics/section_09/f6da1521baeec4bd3bc7a7f1ac4b0856.jpg)

{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

# 1. Compute P(Z<1.48)
pnorm(1.48)

# 2. Plot
norm.trans(0, 1, a=-4, b=1.48)
```
{% endtab %}

{% tab title="Probability" %}
```text
> # 1. Compute P(Z<1.48)
> pnorm(1.48)
## [1] 0.9305634
```
{% endtab %}

{% tab title="Plot" %}
![](../.gitbook/assets/image%20%2825%29.png)
{% endtab %}
{% endtabs %}



**EXAMPLE 5.**  Find the probabilities indicated.

1. _P_\(_Z_ &gt; 1.60\).
2. _P_\(_Z_ &gt; −1.02\).

**\[ Solution \]**

1. Because the events $$Z > 1.60$$ and $$Z ≤ 1.60$$ are complements, the Probability Rule for Complements implies that ****$$P(Z>1.60)=1−P(Z≤1.60)$$.  Since inclusion of the endpoint makes no difference for the continuous random variable $$Z$$ , $$P(Z≤1.60)=P(Z<1.60)$$ , which we know how to find from the table. The number in the row with heading 1.6 and in the column with heading 0.00 is 0.9452.  Thus $$P(Z<1.60)=0.9452.$$  so $$P(Z>1.60)=1−P(Z≤1.60)=1−0.9452=0.0548.$$   Figure 5.11 "Computing a Probability for a Right Half-Line" illustrates the ideas geometrically. Since the total area under the curve is 1 and the area of the region to the left of 1.60 is \(from the table\) 0.9452, the area of the region to the right of 1.60 must be 1−0.9452=0.0548. 

![](../.gitbook/assets/image%20%2826%29.png)

2. The minus sign in −1.02 makes no difference in the procedure; the table is used in exactly the same way as in part \(a\). The number in the intersection of the row with heading −1.0 and the column with heading 0.02 is 0.1539. This means that $$P(Z<−1.02)=P(Z≤−1.02)=0.1539,$$ hence   
$$P(Z>−1.02)=1−P(Z≤−1.02)=1−0.1539=0.8461$$ 

{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

# 1-1. Compute P(Z>1.60)
1-pnorm(1.60)

# 1-2. Plot
norm.trans(0, 1, a=1.60, b=5)

# 2-1. Compute P(Z>-1.02)
1-pnorm(-1.02)

# 2-2. Plot
norm.trans(0, 1, a=-1.02, b=5)
```
{% endtab %}

{% tab title="1. P\(Z>1.60\)" %}
```text
> # 1-1. Compute P(Z>1.60)
> 1-pnorm(1.60)
## [1] 0.05479929
```
{% endtab %}

{% tab title="1. Plot" %}
![](../.gitbook/assets/image%20%28127%29.png)
{% endtab %}

{% tab title="2. P\(Z>-1.02\)" %}
```text
> # 2-1. Compute P(Z>-1.02)
> 1-pnorm(-1.02)
## [1] 0.8461358
```
{% endtab %}

{% tab title="2. Plot" %}
![](../.gitbook/assets/image%20%2856%29.png)
{% endtab %}
{% endtabs %}

\*\*\*\*

**EXAMPLE 6.**  Find the probabilities indicated.

1. $$P(0.5<Z<1.57).$$ 
2. $$P(−2.55<Z<0.09).$$ 

**\[ Solution \]**

1. \*\*\*\*$$P(0.5<Z<1.57)=P(Z<1.57)−P(Z<0.50)=0.9418−0.6915=0.2503$$ ****

![](../.gitbook/assets/image%20%2861%29.png)



2. $$P(−2.55<Z<0.09)==P(Z<0.09)−P(Z<−2.55)=0.5359−0.0054=0.5305$$ 

![](../.gitbook/assets/image%20%28118%29.png)



{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

# 1-1. Compute P(0.5<Z<1.57)
a <- 0.5; b <- 1.57
pnorm(b) - pnorm(a)

# 1-2. Plot
norm.trans(0, 1, a=a, b=b)

# 2-1. Compute P(-2.55<Z<0.09)
a <- -2.55; b <- 0.09
pnorm(b) - pnorm(a)

# 2-2. Plot
norm.trans(0, 1, a=a, b=b)
```
{% endtab %}

{% tab title="1. P\(0.5<Z<1.57\)" %}
```text
> # 1-1. Compute P(0.5<Z<1.57)
> a <- 0.5; b <- 1.57
> pnorm(b) - pnorm(a)
## [1] 0.25033
```
{% endtab %}

{% tab title="1. Plot" %}
```text
> # 1-2. Plot
> norm.trans(0, 1, a=a, b=b)
## Pr(0.5 < X < 1.57) =  0.25033 
## Pr(0.5 < Z < 1.57) =  0.25033 
```

![](../.gitbook/assets/image%20%28182%29.png)
{% endtab %}

{% tab title="2. P\(-2.55<Z<0.09\)" %}
```text
> # 2-1. Compute P(-2.55<Z<0.09)
> a <- -2.55; b <- 0.09
> pnorm(b) - pnorm(a)
## [1] 0.5304702
```
{% endtab %}

{% tab title="2. Plot" %}
```text
> # 2-2. Plot
> norm.trans(0, 1, a=a, b=b)
## Pr(-2.55 < X < 0.09) =  0.5304702 
## Pr(-2.55 < Z < 0.09) =  0.5304702 
```

![](../.gitbook/assets/image%20%2822%29.png)
{% endtab %}
{% endtabs %}



**EXAMPLE 7.**  Find the probabilities indicated.

1. $$P(1.13<Z<4.16).$$ 
2. $$P(−5.22<Z<2.15).$$ 

**\[ Solution \]**

$$1. P(1.13<Z<4.16)==P(Z<4.16)−P(Z<1.13) =1.0000−0.8708=0.1292$$ 

$$2. P(−5.22<Z<2.15)=0.9842−0.0000=0.9842$$ 

{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

# 1-1. Compute P(1.13<Z<4.16)
a <- 1.13; b<- 4.16
pnorm(b) - pnorm(a)

# 1-2. Plot
norm.trans(0, 1, a=a, b=b)

# 2-1. Compute P(-5.22<Z<2.15)
a <- -5.22; b <- 2.15
pnorm(b) - pnorm(a)

# 2-2. Plot
norm.trans(0, 1, a=a, b=b)
```
{% endtab %}

{% tab title="1. P\(1.13<Z<4.16\)" %}
```text
> # 1-1. Compute P(1.13<Z<4.16)
> a <- 1.13; b<- 4.16
> pnorm(b) - pnorm(a)
## [1] 0.1292222
```
{% endtab %}

{% tab title="1. Plot" %}
```text
> # 1-2. Plot
> norm.trans(0, 1, a=a, b=b)
## Pr(1.13 < X < 4.16) =  0.1292222 
## Pr(1.13 < Z < 4.16) =  0.1292222  
```

![](../.gitbook/assets/image%20%28104%29.png)
{% endtab %}

{% tab title="2. P\(-5.22<Z<2.15\)" %}
```text
> # 2-1. Compute P(-5.22<Z<2.15)
> a <- -5.22; b <- 2.15
> pnorm(b) - pnorm(a)
## [1] 0.9842223
```
{% endtab %}

{% tab title="2. Plot" %}
```text
> # 2-2. Plot
> norm.trans(0, 1, a=a, b=b)
## Pr(-5.22 < X < 2.15) =  0.9842223 
## Pr(-5.22 < Z < 2.15) =  0.9842223 
```

![](../.gitbook/assets/image%20%28160%29.png)
{% endtab %}
{% endtabs %}

\*\*\*\*

**EXAMPLE 8.**  Find the probabilities indicated.

1. $$P(−1<Z<1).$$ 
2. $$P(−2<Z<2).$$ 
3. $$P(−3<Z<3).$$ 

**\[ Solution \]**

$$1. P(−1<Z<1)=0.8413−0.1587=0.6826$$ 

$$2. P(−2<Z<2)=0.9772−0.0228=0.9544$$ 

$$3. P(−3<Z<3)=0.9987−0.0013=0.9974$$ 

{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

# 1-1. Compute P(-1<Z<1)
a <- -1; b <- 1
pnorm(b) - pnorm(a)

# 1-2. Plot
norm.trans(0, 1, a=a, b=b)

# 2-1. Compute P(-2<Z<2)
a <- -2; b <- 2
pnorm(b) - pnorm(a)

# 2-2. Plot
norm.trans(0, 1, a=a, b=b)

# 3-1. Compute P(-3<Z<3)
a <- -3; b <- 3
pnorm(b) - pnorm(a)

# 3-2. Plot
norm.trans(0, 1, a=a, b=b)
```
{% endtab %}

{% tab title="1. P\(-1<Z<1\)" %}
```text
> # 1-1. Compute P(-1<Z<1)
> a <- -1; b <- 1
> pnorm(b) - pnorm(a)
## [1] 0.6826895
```
{% endtab %}

{% tab title="1. Plot" %}
```text
> # 1-2. Plot
> norm.trans(0, 1, a=a, b=b)
## Pr(-1 < X < 1) =  0.6826895 
## Pr(-1 < Z < 1) =  0.6826895 
```

![](../.gitbook/assets/image%20%28111%29.png)
{% endtab %}

{% tab title="2. P\(-2<Z<2\)" %}
```text
> # 2-1. Compute P(-2<Z<2)
> a <- -2; b <- 2
> pnorm(b) - pnorm(a)
## [1] 0.9544997
```
{% endtab %}

{% tab title="2. Plot" %}
```text
> # 2-2. Plot
> norm.trans(0, 1, a=a, b=b)
## Pr(-2 < X < 2) =  0.9544997 
## Pr(-2 < Z < 2) =  0.9544997 
```

![](../.gitbook/assets/image%20%2885%29.png)
{% endtab %}

{% tab title="3. P\(-3<Z<3\)" %}
```text
> # 3-1. Compute P(-3<Z<3)
> a <- -3; b <- 3
> pnorm(b) - pnorm(a)
## [1] 0.9973002
```
{% endtab %}

{% tab title="3. Plot" %}
```text
> # 3-2. Plot
> norm.trans(0, 1, a=a, b=b)
## Pr(-3 < X < 3) =  0.9973002 
## Pr(-3 < Z < 3) =  0.9973002 
```

![](../.gitbook/assets/image%20%2894%29.png)
{% endtab %}
{% endtabs %}



## 3. Plotting Probability Curves using R

You may, on some occasion, want to plot a curve or probability distribution. Here are a couple of approaches to plotting a standard normal curve but, they can be used for other probability distributions. The first comes from [Tomas Aragon](http://medepi.com/), the second from [John Fox](http://socserv.mcmaster.ca/jfox/Courses/UCLA/index.html).

### 3-1. using the sequence operator

This approach uses the normal probability formula…

                                 $$f(x)=\frac{1}{\sqrt{2πσ^2}} e^ \frac{−(x−μ)^2} {2σ^2}$$ 

… over a sequence of values.

{% tabs %}
{% tab title="R Code" %}
```
mu <- 0; sigma <- 1 
x <- seq(-4, 4, .01) 
fx <- (1/sqrt(2*pi*sigma^2))*exp(-(x-mu)^2/(2*sigma^2))
plot(x, fx, type = "l", lwd = 2)  
# options type="l"  produces line,  lwd=2 doubles line width
```
{% endtab %}

{% tab title="Plot" %}
![](../.gitbook/assets/image%20%2840%29.png)
{% endtab %}
{% endtabs %}

### 3-2. another approach

Here, we use the `dnorm()`function and add a few bells and whistles.

{% tabs %}
{% tab title="R Code" %}
```
oldpar <- par(mar = c(5, 6, 4, 2) + 0.1)  # room on left
z <- seq(-4, 4, length=1000) 
p <- dnorm(z)
plot(z, p, type="l", lwd=2, 
     main=expression("The Standard Normal Density Function"
    ~~ phi(z)), ylab=expression(phi(z) == frac(1, sqrt(2*pi)) *
     ~~ e^- ~~ frac(z^2, 2)))
abline(h=0, col="gray") ; abline(v=0, col="gray")
z0 <- z[z >= 1.96]    # define region to fill
z0 <- c(z0[1], z0) ;  p0 <- p[z >= 1.96]
p0 <- c(0, p0)
polygon(z0, p0, col="gray")
coords <- locator(2)    # locate head and tail of arrow using your mouse...
arrows(coords$x[1], coords$y[1], coords$x[2], coords$y[2], 
     code=1, length=0.125)
text(coords$x[2], coords$y[2], pos=3, # text above tail arrow
expression(integral(phi(z)*dz, 1.96, infinity) == .025))
```
{% endtab %}

{% tab title="Plot" %}
![](../.gitbook/assets/image%20%28208%29.png)
{% endtab %}
{% endtabs %}

### 3-3. Cumulative Normal Distribution, X ~ N\(0,1\)

{% tabs %}
{% tab title="R Code" %}
```
# Cumulative normal distribution plot, X~N(0,1) 
x <- seq(-3, 3, length=200) 
plot(x, pnorm(x, mean=0, sd=1), 
        type='l', 
        main="Cumulative normal distribution, X~N(0,1)")
abline(h=0, col="gray")
```
{% endtab %}

{% tab title="Plot" %}
![](../.gitbook/assets/image%20%28169%29.png)
{% endtab %}
{% endtabs %}

