# 8-4. Small Sample Tests for a Population Mean

In the previous section hypotheses testing for population means was described in the case of large samples. The statistical validity of the tests was insured by the Central Limit Theorem, with essentially no assumptions on the distribution of the population. 

When sample sizes are small, as is often the case in practice, the Central Limit Theorem does not apply. One must then impose stricter assumptions on the population to give statistical validity to the test procedure. 

**One common assumption** is that the population from which the sample is taken has a normal probability distribution to begin with. Under such circumstances, if the population standard deviation $$\sigma$$ is known, then the test statistic $$(\bar{x}−μ_0) /(σ/\sqrt{n})$$ still has the standard normal distribution, as in the previous two sections. If $$\sigma$$ is unknown and is approximated by the sample standard deviation _s_, then the resulting test statistic $$(\bar{x}−μ_0) /(s/\sqrt{n})$$ follows Student’s _t_-distribution with $$( n−1)$$ degrees of freedom.

> Standardized Test Statistics for Small Sample Hypothesis Tests Concerning a Single Population Mean 
>
> * If  $$σ$$  is known: $$z_o =  \frac {(\bar{x}−μ_0)}{(σ/\sqrt{n})}$$
> * If  $$σ$$  is unknown: $$t_o =  \frac {(\bar{x}−μ_0)}{(s/\sqrt{n})}$$
>
> The first test statistic \( $$σ$$ known\) has the standard normal distribution.
>
> The second test statistic \($$σ$$ unknown\) has Student’s _t_-distribution with $$(n−1)$$ degrees of freedom. 
>
> The population must be normally distributed.

The distribution of the second standardized test statistic \(the one containing _s_\) and the corresponding rejection region for each form of the alternative hypothesis \(left-tailed, right-tailed, or two-tailed\), is shown in Figure 8.11 "Distribution of the Standardized Test Statistic and the Rejection Region". This is just like Figure 8.4 "Distribution of the Standardized Test Statistic and the Rejection Region", except that now the critical values are from the _t_-distribution. Figure 8.4 "Distribution of the Standardized Test Statistic and the Rejection Region" still applies to the first standardized test statistic \(the one containing _σ_\) since it follows the standard normal distribution.

Figure 8.11 Distribution of the Standardized Test Statistic and the Rejection Region

![](https://saylordotorg.github.io/text_introductory-statistics/section_12/ecf5f771ca148089665859c88d8679df.jpg)

The _p_-value of a test of hypotheses for which the test statistic has **Student’s** _**t**_**-distribution** can be computed using statistical software, but it is impractical to do so using tables, since that would require 30 tables analogous to Figure 12.2 "Cumulative Normal Probability", one for each degree of freedom from 1 to 30. Figure 12.3 "Critical Values of " can be used to approximate the _p_-value of such a test, and this is typically adequate for making a decision using the _p_-value approach to hypothesis testing, although not always. 

For this reason the tests in the two examples in this section will be made following the **critical value approach** to hypothesis testing summarized at the end of Section 8.1 "The Elements of Hypothesis Testing", but after each one we will show how the _**p**_**-value approach** could have been used.



**EXAMPLE 10.** The price of a popular tennis racket at a national chain store is $179. Portia bought five of the same racket at an online auction site for the following prices:

                                                             155  179  175  175  161 

Assuming that the auction prices of rackets are normally distributed, determine whether there is sufficient evidence in the sample, at the 5% level of significance, to conclude that the average price of the racket is less than $179 if purchased at an online auction.

**\[ Solution \]**

* **Step 1**. The hypothesis test is                $$H0:μ=179  vs. Ha:μ<179, @ α=0.05$$ 
* **Step 2.** The sample is small and the population standard deviation is unknown.   
                Thus the test statistic is  
                 $$t_o =  \frac {(\bar{x}−μ_0)}{(s/\sqrt{n})}$$

  and has the Student _t_-distribution with $$(n−1)=(5−1)=4$$ degrees of freedom.

* **Step 3**. From the data we compute $$\bar{x}=169$$ and $$s = 10.39$$ .                Inserting these values into the formula for the test statistic gives              $$t_o =  \frac {(\bar{x}−μ_0)}{(s/\sqrt{n})} =  \frac {(169−179)}{10.39/\sqrt{5}}  = -2.152$$
* **Step 4.** Since the symbol in _Ha_ is “&lt;” this is a left-tailed test, so there is a single critical value, $$−t_α=−t_{0.05}[df=4]$$ . Reading from the row labeled $$df=4$$ in Figure 12.3 "Critical Values of " its value is −2.132. The rejection region is $$(−∞,−2.132].$$ 
* **Step 5.** As shown in Figure 8.12 "Rejection Region and Test Statistic for " the test statistic falls in the rejection region. **The decision is to reject** $$H_0$$ . 
* In the context of the problem our **conclusion** is:

  _The data provide sufficient evidence, at the 5% level of significance, to conclude that the average price of such rackets purchased at online auctions is less than $179._

Figure 8.12 Rejection Region and Test Statistic for Note 8.42 "Example 10"

![](https://saylordotorg.github.io/text_introductory-statistics/section_12/37a4f201cad923d15a8bfab828bd7640.jpg)

{% tabs %}
{% tab title="R Source" %}
```text
n <- 5
xb <- 169
m0 <- 179
sd <- 10.39
alpha <- 0.05

# in case of left-tail test
se <- sd / sqrt(n)

t_c <- qt(1-alpha, n-1); t_c
t_o <- (xb-m0)/se; t_o

if (t_o <= -t_c) cat("Reject Ho.\n") else 
                 cat ("Can not reject Ho.\n")
```
{% endtab %}

{% tab title="Result" %}
```text
> t_c <- qt(1-alpha, n-1); t_c
## [1] 2.131847
> t_o <- (xb-m0)/se; t_o
## [1] -2.152135
> 
> if (t_o <= -t_c) cat("Reject Ho.\n") else 
+                  cat ("Can not reject Ho.\n")
## Reject Ho.
```
{% endtab %}
{% endtabs %}

To perform the test in Note 8.42 "Example 10" using the _**p**_**-value approach**, look in the row in Figure 12.3 "Critical Values of " with the heading $$df=4$$ and search for the two _t_-values that bracket the unsigned value 2.152 of the test statistic. They are 2.132 and 2.776, in the columns with headings $$t_{0.050}$$ and $$t_{0.025}$$ . They cut off right tails of area 0.050 and 0.025, so because 2.152 is between them it must cut off a tail of area between 0.050 and 0.025. 

By symmetry −2.152 cuts off a left tail of area between 0.050 and 0.025, hence the _p_-value corresponding to $$t=−2.152$$ is between 0.025 and 0.05. Although its precise value is unknown, it must be less than $$α=0.05$$ , so the decision is **to reject** $$H_0$$ .

* Using **Rstat** Package : `meantest2.plot()`

{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

meantest2.plot(xb=169, mu0=179, sig=10.39, n=5, side="low")
```
{% endtab %}

{% tab title="Result" %}
```text
> meantest2.plot(xb=169, mu0=179, sig=10.39, n=5, side="low")
T0 = (169 - 179) / (10.39/√5) = -2.1521 
P-v = P(T < T0) = 0.0489 
```
{% endtab %}

{% tab title="Plot" %}
![](../.gitbook/assets/image%20%28141%29.png)

**\[Decision Rule\]**

* p-value=0.0489 =&gt; if p-value is less than alpha\(=0.05\), **reject Ho**. Otherwise, Can not reject Ho.
{% endtab %}
{% endtabs %}



**EXAMPLE 11.** A small component in an electronic device has two small holes where another tiny part is fitted. In the manufacturing process the average distance between the two holes must be tightly controlled at 0.02 mm, else many units would be defective and wasted. Many times throughout the day quality control engineers take a small sample of the components from the production line, measure the distance between the two holes, and make adjustments if needed. Suppose at one time four units are taken and the distances are measured as

                                                                    0.021   0.019   0.023   0.020  

Determine, at the 1% level of significance, if there is sufficient evidence in the sample to conclude that an adjustment is needed. Assume the distances of interest are normally distributed.

**\[ Solution \]**

* **Step 1**. The relevant test is               $$H_0:μ=0.02 vs. H_a:μ=≠0.02, @ α=0.01$$                where _μ_ denotes the mean distance between the holes.
* **Step 2**. The sample is small and the population standard deviation is unknown.   
                Thus the test statistic is  
                $$t_o =  \frac {(\bar{x}−μ_0)}{(s/\sqrt{n})}$$

                and has the **Student** _**t**_**-distribution** with $$(n−1)=(4−1)=3$$ degrees of freedom.

* **Step 3.** From the data we compute $$\bar{x}=0.02075$$ and $$s = 0.00171.$$                Inserting these values into the formula for the test statistic gives               $$t_o =  \frac {(\bar{x}−μ_0)}{(s/\sqrt{n})} =  \frac {(0.02075−0.02)}{0.00171/\sqrt{4}} = 0.877$$
* **Step 4.** Since the symbol in $$H_a$$ is “ $$≠$$ ” this is a **two-tailed test**,                so there are **two critical values**, $$±t_{α∕2}=±t_{0.005}[df=3].$$                Reading from the row in Figure 12.3 "Critical Values of " labeled $$df=3$$                their values are $$±5.841.$$                The rejection region is $$(−∞,−5.841]∪[5.841,∞).$$ 
* **Step 5.** As shown in Figure 8.13 "Rejection Region and Test Statistic for " **the test statistic does not fall in the rejection region**. The decision is **not to rejec**t $$H_0$$ . 
* In the context of the problem our **conclusion** is:

  _The data do not provide sufficient evidence, at the 1% level of significance, to conclude that the mean distance between the holes in the component differs from 0.02 mm._

Figure 8.13 Rejection Region and Test Statistic for Note 8.43 "Example 11"

![](https://saylordotorg.github.io/text_introductory-statistics/section_12/ac90ded7d10c3b0d2ccfb5daea47745f.jpg)

{% tabs %}
{% tab title="R Source" %}
```text
n <- 4
xb <- 0.02075
m0 <- 0.02
sd <- 0.00171
alpha <- 0.01

# in case of two-tail test
se <- sd / sqrt(n)

t_c <- qt(1-alpha/2, n-1); t_c
t_o <- (xb-m0)/se; t_o

if (t_o <= -t_c || t_o >= t_c ) cat("Reject Ho.\n") else 
                                cat ("Can not reject Ho.\n")
```
{% endtab %}

{% tab title="Result" %}
```text
> t_c <- qt(1-alpha/2, n-1); t_c
## [1] 5.840909
> t_o <- (xb-m0)/se; t_o
## [1] 0.877193
> 
> if (t_o <= -t_c || t_o >= t_c ) cat("Reject Ho.\n") else 
+                                 cat ("Can not reject Ho.\n")
## Can not reject Ho.
```
{% endtab %}
{% endtabs %}



 To perform the test in Note 8.43 "Example 11" using the _**p**_**-value approach**, look in the row in Figure 12.3 "Critical Values of " with the heading $$df=3$$ and search for the two _t_-values that bracket the value 0.877 of the test statistic. Actually 0.877 is smaller than the smallest number in the row, which is 0.978, in the column with heading $$t_{0.200}$$ . The value 0.978 cuts off a right tail of area 0.200, so because 0.877 is to its left it must cut off a tail of area greater than 0.200. 

Thus the _p_-value, which is the double of the area cut off \(since the test is two-tailed\), is greater than 0.400. Although its precise value is unknown, it must be greater than $$α=0.01$$ , so the decision is not to reject $$H_0$$ .

* Using Rstat Package : `meantest2.plot()`

{% tabs %}
{% tab title="R Source" %}
```text
library(Rstat)

meantest2.plot(xb=0.02075, mu0=0.02, sig=0.00171, n=4, side="two")
```
{% endtab %}

{% tab title="Result" %}
```text
> meantest2.plot(xb=0.02075, mu0=0.02, sig=0.00171, n=4, side="two")
## T0 = (0.0208 - 0.02) / (0.0017/√4) = 0.8772 
## P-v = 2×P(T > |T0|) = 0.445 
```
{% endtab %}

{% tab title="Plot" %}
![](../.gitbook/assets/image%20%28119%29.png)

**\[Decision Rule\]**

* p-value=0.445 =&gt; if p-value is less than alpha\(=0.01\), reject Ho. Otherwise, **Can not reject Ho.**
{% endtab %}
{% endtabs %}

